FROM mcr.microsoft.com/mssql/server:2022-latest

COPY init_sql.sql /docker-entrypoint-initdb.d/
COPY entrypoint.sh /usr/local/bin/mssql-entrypoint.sh

USER root
RUN chmod +x /usr/local/bin/mssql-entrypoint.sh
USER mssql

ENTRYPOINT ["/usr/local/bin/mssql-entrypoint.sh"]